#!/bin/bash
RIGHTS=$1
BASENAME=$2
USERLIST=$3
totalrole="$RIGHTS$BASENAME"

for i in $USERLIST; do
psql -U $POSTGRES_USER -d $BASENAME -t -c "GRANT $totalrole TO $i; \
    ALTER DEFAULT PRIVILEGES FOR ROLE $i IN SCHEMA public GRANT SELECT ON TABLES TO read_$BASENAME; \
    ALTER DEFAULT PRIVILEGES FOR ROLE $i IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO read_$BASENAME; \
    ALTER DEFAULT PRIVILEGES FOR ROLE $i IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO write_$BASENAME; \
    ALTER DEFAULT PRIVILEGES FOR ROLE $i IN SCHEMA public GRANT ALL ON SEQUENCES TO write_$BASENAME; \
    ALTER DEFAULT PRIVILEGES FOR ROLE $i IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO admin_$BASENAME; \
    ALTER DEFAULT PRIVILEGES FOR ROLE $i IN SCHEMA public GRANT ALL ON SEQUENCES TO admin_$BASENAME;"
done
